[build]
    functions = "src"
    command="netlify deploy --prod"
    publish="."

[[redirects]]
    to="/.netlify/functions/server/:splat"
    from="/*"
    status=200

[functions]
    external_node_modules = ["mongodb", "express"]
    node_bundler = "esbuild"