[build]
    functions = "src"
    publish="."
    # context="production"
    # port=1732

[[redirects]]
    to="/.netlify/functions/server/:splat"
    from="/*"
    status=200

[functions]
    external_node_modules = ["mongodb", "express"]
    node_bundler = "esbuild"