[functions]
    external_node_modules = ["mongodb", "express"]
    node_bundler = "esbuild"

[build]
    functions = "src"
    command="npm run build"
    context="production"
    build=true
    debug=true
    prod=true
    # port=1732

[context.production.environment]
    NODE_ENV = "production"

[build.environment]
  NODE_VERSION = "18.x"

[[redirects]]
    to="/.netlify/functions/server/:splat"
    from="/api/v1/*"
    status=200

[[headers]]
    for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
